---
title:   "| Prostitution\n| PL 230.00\n \n"
author: "Planning and Management"
date: "`r format(Sys.time(),'%B  %d, %Y')`"
output: pdf_document
geometry: margin=.5in
fontsize: 12pt
always_allow_html: yes
header-includes:
- \usepackage[utf8]{inputenc}
- \usepackage[T1]{fontenc}
- \usepackage[english]{babel}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
editor_options: 
  chunk_output_type: console
---


```{r setup,include=F, eval = T}
knitr::opts_chunk$set(eval = F, echo = F,warning=F,message=F,cache=F,fig.width=12,fig.height=8)
knitr::knit_hooks$set(inline = function(x) { prettyNum(x, big.mark=",") })

set.seed(813)


pkgs <- c("tidyverse", "here", "DescTools", "skimr",
          "lubridate", "sjmisc", "tictoc", "purrr",
          "xtable", "ggalt", "knitr", "kableExtra", "janitor",
          "scales", "Cairo", "dplyr", "feather")

options(scipen=1000)
#Report: https://www.cookcountystatesattorney.org/sites/default/files/files/documents/ccsao_2017_data_report_180220.pdf


lapply(pkgs, require, character.only = T)
tic()
# library(sqldf);library(DescTools);library(purrr);library(ggplot2)
# library(stringr);library(forcats);library(xtable);library(ggalt)
# library(knitr);library(kableExtra);library(janitor);library(scales);
# library(Cairo)

#Set to current working directory here
#setwd("P:/Bureau Data/PLANNING/Data Requests/Example File Path")
options(scipen = 1000,stringsAsFactors = FALSE)
#================
#Import and Clean
#================

infile <- here::here("data", "dataset.feather")
d <- read_feather(infile)


# dms <- odbcConnect("dms")
# d <- sqlQuery(dms,"select distinct * from ##patronizing") #UNIQUE-TO-QUERY ##TABLE NAME FOR R

#Character for grouping
# d$ScreenYear <- as.character(d$ScreenYear)
# 
# #Flags for counting
# d <- d  %>% 
#   filter(!is.na(DefendantID)) %>% 
#   mutate(CasesCommenced = ifelse(is.na(DefendantID)==F,1,0),
#          CasesDeclined = ifelse(IsDP==1,1,0),
#          CasesCharged = ifelse(IsDP==0,1,0),
#          CasesArraignSupreme = ifelse(is.na(ARCSurvive) & Indicted==1,1,0),
#          CasesArraigned = ifelse(IsDP==0 & is.na(ARCSurvive)==F,1,0),
#          CasesDisposedArraignment = ifelse(ARCSurvive==0,1,0),
#          CasesSurvivingArraignment = ifelse(ARCSurvive==1,1,0),
#          CasesIndicted = ifelse(Indicted==1,1,0),
#          CasesDisposed = ifelse(is.na(DspCondensed)==F,1,0),
#          CasesSentenced = ifelse(DspCondensed %in% c("Plea","Convicted"),1,0),
#          CasesDismissed = ifelse(DspCondensed %in% c("Evidence Dismissal","30.30 Speedy",
#                                                      "Other Non ACD/M Dismissal","ACD/M Dismissal"),1,0),
#          CasesDismissedACD = ifelse(DspCondensed %in% c("ACD/M Dismissal"),1,0),
#          CasesDismissedNONACD = ifelse(DspCondensed %in% c("Evidence Dismissal","30.30 Speedy",
#                                                            "Other Non ACD/M Dismissal"),1,0),
#          CasesBWO = ifelse(CaseStatus=="Outstanding Bench Warrant", 1,0))

```


```{r generic summary,echo=F,results='asis', eval = T}

#================
#Screen
#================

# glimpse(d)
# Desc(d$EVENT)
# Desc(d$EVENT~d$disp)
# 
# 
# d %>% 
#   group_by(EVENT,disp) %>% 
#   tally(sort=T)

screen <-   d %>%
  group_by(arrest_year) %>%
  summarise(`Commenced` = n_distinct(CASE_PARTICIPANT_ID),
            `via Preliminary Hearing`=sum(`EVENT_Preliminary Hearing`),
            `via Indictment` = sum(EVENT_Indictment)
            # `Nolle Pros.` = sum(ifelse(),na.rm = T),
            # `Charged` = sum(CasesCharged,na.rm = T),
            # `Not Arraigned - SCA or SCI` = sum(CasesArraignSupreme,na.rm = T),
            # `Arraigned` = sum(CasesArraigned,na.rm = T),
            # `Disposed at Arr.` = sum(CasesDisposedArraignment,na.rm = T),
            # `Survived Arr.` = sum(CasesSurvivingArraignment,na.rm = T),
            # `Indicted` = sum(CasesIndicted,na.rm = T),
            # `Pled Guilty or Convicted` = sum(CasesSentenced,na.rm = T),
            # `Dismissed` = sum(CasesDismissed,na.rm = T),
            # `ACD` = sum(CasesDismissedACD,na.rm = T),
            # `Non-ACD` = sum(CasesDismissedNONACD,na.rm = T),
            # `Outstanding Bench Warrant` = sum(CasesBWO, na.rm = T)
            ) %>%
  t() %>%
  as.data.frame() %>%
  #as_tibble() %>% 
  rownames_to_column(var = " ") %>%
  set_names(.[1,-1] %>% unlist() %>% as.numeric() %>% as.character() %>% c(" ",.)) %>% 
  filter(` `!="arrest_year") %>% 
  mutate_at(vars(-1),as.numeric) %>%
  mutate(Total = rowSums(.[,2:ncol(.)]))

#================
#Dsp
#================

# dsp <- d %>%
#   filter(CasesDisposed==1) %>%
#   group_by(ScreenYear,DspCondensed) %>%
#   summarise(Dispositions = n()) %>%
#   spread(DspCondensed,Dispositions,fill = 0) %>%
#   ungroup() %>%
#   mutate(`Plea (%)` = `Plea`/rowSums(.[,2:ncol(.)]),
#          `Convicted (%)` = `Convicted`/rowSums(.[,2:ncol(.)]),
#          `ACD/M Dismissal (%)` = `ACD/M Dismissal`/rowSums(.[,2:ncol(.)]),
#          `30.30 Speedy (%)` = `30.30 Speedy`/rowSums(.[,2:ncol(.)]),
#          `Evidence Dismissal (%)` = `Evidence Dismissal`/rowSums(.[,2:ncol(.)]),
#          `Other Non ACD/M Dismissal (%)` = `Other Non ACD/M Dismissal`/rowSums(.[,2:ncol(.)]),
#          #`Acquitted (%)` = `Acquitted`/rowSums(.[,2:ncol(.)]),
#          #`Other (%)` = `Other`/rowSums(.[,2:ncol(.)]),
#          Disposed = rowSums(.[,2:ncol(.)]))  %>%
#   select(ScreenYear,
#          `Plea`,`Plea (%)`,
#          `Convicted`,`Convicted (%)`,
#          `ACD/M Dismissal`,`ACD/M Dismissal (%)`,
#          `30.30 Speedy`,`30.30 Speedy (%)`,
#          `Evidence Dismissal`,`Evidence Dismissal (%)`,
#          `Other Non ACD/M Dismissal`,`Other Non ACD/M Dismissal (%)`,
#          #`Acquitted`,`Acquitted (%)`,
#          #`Other`,`Other (%)`,
#          Disposed) %>% 
#   t() %>%
#   as.data.frame() %>%
#   as_tibble() %>% 
#   rownames_to_column(var = " ") %>%
#   set_names(.[1,-1] %>% unlist() %>% as.numeric() %>% as.character() %>% c(" ",.)) %>% 
#   filter(` `!="ScreenYear") %>% 
#   mutate_at(vars(-1),as.numeric) %>%
#   mutate(Total = case_when(grepl("%",` `)==T ~
#                              lag(rowSums(.[,2:ncol(.)]))/
#                              rowSums(.[nrow(.),2:ncol(.)]),
#                            TRUE ~
#                              rowSums(.[,2:ncol(.)]))) %>%
#   mutate_at(vars(-1),funs(ifelse(grepl("%",` `)==T,paste0(round(100*.,1),"%"),comma(.,digits = 0))))

#================
#Sen
#================

# sen <- d %>%
#   filter(CasesSentenced==1) %>%
#   group_by(ScreenYear,SentenceType) %>%
#   summarise(Sentences = n()) %>%
#   spread(SentenceType,Sentences,fill = 0) %>%
#   ungroup() %>%
#   mutate(`Fine (%)` = `Fine`/rowSums(.[,2:ncol(.)]),
#          `Jail (%)` = `Jail`/rowSums(.[,2:ncol(.)]),
#          ` Probation (%)` = `Probation`/rowSums(.[,2:ncol(.)]),
#          `Conditional Discharge (%)` = `Conditional Discharge`/rowSums(.[,2:ncol(.)]),
#          `Community Service (%)` = `Community Service`/rowSums(.[,2:ncol(.)]),
#          `Day Custody Program (%)` = `Day Custody Program`/rowSums(.[,2:ncol(.)]),
#          `Time Served (%)` =  `Time Served`/rowSums(.[,2:ncol(.)]),
#          `Other (%)` = `Other`/rowSums(.[,2:ncol(.)]),
#          Sentenced = rowSums(.[,2:ncol(.)])) %>%
#   select(ScreenYear,
#          `Fine`,`Fine (%)`,
#          `Jail`,`Jail (%)`,
#          `Probation`,` Probation (%)`,
#          `Conditional Discharge`,`Conditional Discharge (%)`,
#          `Community Service`,`Community Service (%)`,
#          `Day Custody Program`,`Day Custody Program (%)`,
#          `Time Served`,`Time Served (%)`,
#          `Other`,`Other (%)`,
#          Sentenced) %>% 
#   t() %>%
#   as.data.frame() %>% 
#   as_tibble() %>% 
#   rownames_to_column(var = " ") %>%
#   set_names(.[1,-1] %>% unlist() %>% as.numeric() %>% as.character() %>% c(" ",.)) %>% 
#   filter(` `!="ScreenYear") %>% 
#   mutate_at(vars(-1),as.numeric) %>%
#   mutate(Total = case_when(grepl("%",` `)==T ~
#                              lag(rowSums(.[,2:ncol(.)]))/
#                              rowSums(.[nrow(.),2:ncol(.)]),
#                            TRUE ~
#                              rowSums(.[,2:ncol(.)]))) %>%
#   mutate_at(vars(-1),funs(ifelse(grepl("%",` `)==T,paste0(round(100*.,1),"%"),comma(.,digits = 0))))

#================
#Inline, printing changes
#================

#Save friendlies for inline reference
#dspfriendly <- dsp
#senfriendly <- sen

#Only required when you have percentage signs and want to indent. If you want to indent, you need to dive into Latex and escape the special character of %.
#dsp[] <- lapply(dsp,gsub,pattern = "%",replacement = "\\%",fixed = T)
#sen[] <- lapply(sen,gsub,pattern = "%",replacement = "\\%",fixed = T)

```


```{r report specific requests,echo=F,results='asis', eval = F}

#================
#Disposition Charges
#================

dsp_code <- d %>%
  filter(CasesSentenced==1) %>%
  mutate(DspCharge = ifelse(is.na(DspCharge),"Awaiting Sentence",DspCharge)) %>% 
  group_by("Disposition Charge Statute" = fct_lump(fct_infreq(as_factor(DspCharge)),prop = .01,
                                                   other_level = "Statutes Less Than 1%")) %>%
  summarise("Defendants" = n_distinct(DefendantID)) %>%
  mutate("Defendants (%)" = percent(Defendants/sum(Defendants))) %>%
  arrange(`Disposition Charge Statute`) %>% 
  adorn_totals(which = "row")

```


```{r, eval = F}

###Screenings and Arraignments  
This report summarizes `r nrow(d)` Prostitution arrests between 2010 and 2017. DANY declined to prosecute a very small number of cases - only `r screen[screen$" "=="Declined",names(screen)=="Total"]` over the entire period. `r percent(round(screen[screen$" "=="Disposed at Arr.", names(screen)=="Total"]/screen[screen$" "=="Arraigned", names(screen)=="Total"],3) %>% pull())` of arraigned cases were disposed at arraignment. Of cases that survived arraignment, `r percent(round(screen[screen$" "=="Indicted", names(screen)=="Total"]/screen[screen$" "=="Survived Arr.", names(screen)=="Total"],3) %>% pull())` were indicted. `r percent(round(screen[screen$" "=="Pled Guilty or Convicted", names(screen)=="Total"]/as.numeric(gsub(",","",dsp[dsp$" "=="Disposed", names(dsp)=="Total"])),3) %>% pull())` of disposed cases resulted in a plea or conviction, while `r percent(round(screen[screen$" "=="Dismissed", names(screen)=="Total"]/as.numeric(gsub(",","",dsp[dsp$" "=="Disposed", names(dsp)=="Total"])),3) %>% pull())` resulted in a dismissal.
```


```{r,echo=F, results='asis', eval = T}

kable(screen,format = "latex",booktabs = T,
      align = c("l",rep("c",ncol(screen))),digits = 0,
      format.args = list(big.mark = ","),linesep = "",
      caption = "Prostitution Arrests, 2010 - 2017") %>%
  kable_styling(latex_options = c("striped","HOLD_position")) %>% 
  add_indent(c(which(screen$` ` %in% c("via Preliminary Hearing", "via Indictment","Declined","Charged",
                                       "Disposed at Arr.","Survived Arr.",
                                       "ACD","Non-ACD"))))

```

###Dispositions

```{r,echo=F,results='asis', eval = F}

kable(dsp,format = "latex",booktabs = T,
      align = c("l",rep("c",ncol(dsp))),digits = 0,
      format.args = list(big.mark = ","),linesep = "",
      caption = "Prostitution Dispositions, 2010 - 2017") %>%
  kable_styling(latex_options = c("striped","HOLD_position","scale_down")) %>%
  add_indent(c(which(grepl("%",dsp$` `)==T))) %>% 
  row_spec(nrow(dsp),bold = T) %>% 
  row_spec(nrow(dsp)-1,hline_after = T)

```

###Disposition Charges

```{r,echo=F,results='asis', eval = F}

kable(dsp_code,format = "latex",booktabs = T,
      align = c("l",rep("c",ncol(dsp_code))),digits = 0,
      format.args = list(big.mark = ","),linesep = "",
      caption = "Disposition Charges Greater Than 1\\% of Total") %>% #If necessary escape values in title
  kable_styling(latex_options = c("striped","HOLD_position")) %>%
  row_spec(nrow(dsp_code),bold = T) %>% 
  row_spec(nrow(dsp_code)-1,hline_after = T)

```

###Sentences

```{r,echo=F,results='asis', eval = F}

kable(sen,format = "latex",booktabs = T,
      align = c("l",rep("c",ncol(sen))),digits = 0,
      format.args = list(big.mark = ","),linesep = "",
      caption = "Prostitution Sentences, 2010 - 2017") %>%
  kable_styling(latex_options = c("striped","HOLD_position","scale_down")) %>%
  add_indent(c(which(grepl("%",sen$` `)==T))) %>% 
  row_spec(nrow(sen),bold = T) %>% 
  row_spec(nrow(sen)-1,hline_after = T)
         
```




```{r}
toc()

```